# Generated by Django 5.2.5 on 2025-10-09 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_builder_approved'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='builder_approved',
            new_name='builder_approve',
        ),
    ]
