# Generated by Django 5.2.5 on 2025-10-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_rename_builder_approved_builder_approve'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=200)),
                ('property_location', models.CharField(max_length=200)),
                ('property_price', models.CharField(max_length=200)),
                ('user_id', models.CharField(max_length=200)),
                ('user_name', models.CharField(max_length=200)),
                ('user_phone', models.CharField(max_length=200)),
                ('user_email', models.CharField(max_length=200)),
            ],
        ),
    ]
