# Generated by Django 5.2.5 on 2025-10-10 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property_Detailss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_photo', models.ImageField(upload_to='')),
                ('builder_id', models.CharField(max_length=200)),
                ('property_category', models.CharField(max_length=200)),
                ('property_name', models.CharField(max_length=200)),
                ('property_location', models.CharField(max_length=200)),
                ('property_budget', models.CharField(max_length=200)),
                ('bedrooms', models.CharField(max_length=200)),
                ('bathrooms', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=200)),
                ('floor', models.CharField(max_length=200)),
                ('parking', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Property_Details',
        ),
    ]
